name: Deploy to Heroku (Backend)

on:
  push:
    branches:
      - main
    paths:
      - "packages/backend/**"
      - ".github/workflows/backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Adding Heroku remote
      #   run: heroku git:remote -a ${{ secrets.HEROKU_BACKEND_APP_NAME }}
      # - name: Cloning Heroku repo
      #   run: heroku git:clone -a ${{ secrets.HEROKU_BACKEND_APP_NAME }}
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_TOKEN }}
          heroku_app_name: ${{ secrets.HEROKU_BACKEND_APP_NAME }}
          heroku_email: ${{ secrets.MY_HEROKU_EMAIL }}
          appdir: "packages/backend"
